### ISSUE TITLE
Game freezing(Hosted multiplayer)

### ISSUE THREAD

**Issue by Sneedstar** [Lanboost/TModLoader_LansUnlimitedBuffSlots#2]
Mod is not compatible with custom mod buffs, loading into a hosted multiplayer will cause your character to freeze and unable to move or attack.

**Comment by Sneedstar** [comment]
I do not recommend using this mod if you have all the big mods installed and especially if you want it to be multiplayer. Big mods may include Calamity, thorium, Elements, Enigma, Antiaris etc.

**Comment by Lanboost** [comment]
Closing due to 2 years old.
