### ISSUE TITLE
Incompatibility with Industrial Pickaxes v4.3.1

### ISSUE THREAD

**Issue by AndreLouisIssa** [Lanboost/TModLoader_LansUnlimitedBuffSlots#3]
Issue Type: Compatibility, Non-Permanent, World Gen, World, Tiles
Issue:
- Cannot create any new worlds, halts at "Adding even more Plants!"
- After loading an existing world I cannot break any tiles (but can place tiles)

Likely Cause:
- Something in this mod causes something in IP to fail inside their function responsible for breaking tiles      

Motivation:
- IP has had issues with this exact outcome from other causes
- There are other mods that also cause this issue in combination with IP

Conclusion:
- The fault rests on Industrial Pickaxes as it seems the cause is common enough that it is incompatible in this way with multiple mods.
- It may still be possible that the issue could be resolved from your end but will not solve the issue for all cases.

You can close this issue whenever you want because it's not your fault so I don't expect you to patch from your end. I just want the report on record so you know if you see an issue like this from someone else you have a better idea of what the cause is.

**Comment by AndreLouisIssa** [comment]
This issue also exists when `No Buff Limit` is combined with Industrial Pickaxes so it seems to be related to the core of this mod's feature that being altering the buff slots.

**Comment by keostar** [comment]
i had the same issue but it stopped on generating minecart tracks but it fixed its self some how

**Comment by keostar** [comment]
also bombs don't explode correctly they either don't explode and disappear or they explode and nothing is done to the world or charater

**Comment by Lanboost** [comment]
Closing due to 2 years old.
